repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.8.0 
    hooks:
      - id: black
        args: ["--line-length=79"]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4 
    hooks:
      - id: autopep8
        args: ["--in-place", "--aggressive", "--aggressive"]
